### ISSUE TITLE
EfficientReLU

### ISSUE THREAD

**Issue by yifita** [gpleiss/efficient_densenet_pytorch#10]
maybe it's not the best place to ask this, but I thought I would be able to get some insight from the author directly :)
You used _EfficientReLU where you called the backend operations, is this necessary? What is the gain here, could I simply substitute it with nn.ReLU?
My intention is to change the type of activation here, wonder whether i can do it in a simpler way.

**Comment by taineleau** [comment]
@yifita It's necessary! You have to manually backward the ReLU [on Line 283](https://github.com/gpleiss/efficient_densenet_pytorch/blob/master/models/densenet_efficient.py#L283) after re-compute the BN layer. Hence, what we do here's not consistent with torch.nn's design: the backward pass is transparent to the user, so we have to explicitly call the backend operations. 
Hope this explanation help!

**Comment by taineleau** [comment]
@yifita btw, feel free to give a feedback on using other activation.
