### ISSUE TITLE
error rate compute in demo.py

### ISSUE THREAD

**Issue by a2889184** [gpleiss/efficient_densenet_pytorch#12]
Hi, thanks for this efficient densenet code.

But I found a probable mistake in demo.py at line 112:
`error = 1 - torch.eq(predictions_var, target_var).float().mean()`
it might have to be corrected to:
`error = 1 - torch.eq(predictions_var.view(-1), target_var).float().mean()`

Because the size of predictions_var and target_var are (train_size, 1) and (train_size, ), `torch.eq(...)` will return a train_size * train_size matrix, and its entries are almost 0 (only 1 at diagonal). Then the error rate will not able to decrease.

**Comment by taineleau** [comment]
Hi, are you using PyTorch 0.2?

**Comment by a2889184** [comment]
My PyTorch version is 0.2.0+925208a, I installing it from source.

**Comment by mosttl** [comment]
I met the same problem with the latest PyTorch (v0.2.0) installed, and also figured out the same solution.

**Comment by taineleau** [comment]
The code currently is based on PyTorch v0.1.12. We will release the code for the latest PyTorch version soon. Please kindly use v0.1.12 for now. Thanks!
