### ISSUE TITLE
Efficient Conv3d Class

### ISSUE THREAD

**Issue by ahkarami** [gpleiss/efficient_densenet_pytorch#14]
Hi @gpleiss , thanks for this efficient densenet code.
Would you please kindly, implement an '_Efficient Conv3d Class_'? 
I will really appreciate if you can provide some guidance to me for implementing this class based on your 'EfficientConv2d' class.

**Comment by gpleiss** [comment]
Have you implemented a 3D convolution DenseNet already (not memory-efficient)?
I imagine it should be pretty similar to adapt my repo to 3 dimensions - just replace `Conv2d`, `BatchNorm2d`, and `AvgPool2d` with their respective `3d` layers.

**Comment by ahkarami** [comment]
Thank you. I got it.
