### ISSUE TITLE
Is there any memory-efficient tensorflow Implementation？

### ISSUE THREAD

**Issue by feynman233** [gpleiss/efficient_densenet_pytorch#15]
Hi, I have found the same problem about the GPU memory，and  is there any memory-efficient tensorflow Implementation？
Thanks very much!

**Comment by gpleiss** [comment]
No TensorFlow implementation at the moment, sorry!

**Comment by joeyearsley** [comment]
https://github.com/joeyearsley/efficient_densenet_tensorflow
