### ISSUE TITLE
The efficient implementation do not compatible with parallel computing

### ISSUE THREAD

**Issue by Vandermode** [gpleiss/efficient_densenet_pytorch#2]
Hi, I run the demo in this repo without changing anything except the cifar data directory. However, it raised a Runtime: `RuntimeError: tensors are on different GPUs`. Then I tried the naive implementation with command line flag --efficient=False, it actually worked fine. By the way, the efficient implementation can work well after I modify the code to not use `torch.nn.DataParallel`. Do you actually test your implementation in multiple GPU? I guess since you manually change the behaviour of gradient flow, something wrong...

**Comment by taineleau** [comment]
Hi, I have fixed this in my fork version and I will make a PR by the end of this week. Thanks.

**Comment by taineleau** [comment]
@Vandermode Hi, I have updated the code for your convenience. Hope you enjoy it!

**Comment by Vandermode** [comment]
@taineleau Oh, thanks, I will test it later.
