### ISSUE TITLE
Why the Error is very high?

### ISSUE THREAD

**Issue by tryerrorman** [gpleiss/efficient_densenet_pytorch#20]
I run the demo on cifar 10 and have got the result show below. I found the error is around 0.9 in all the epoches. And the final error is very high(0.897). Is it right?
`
Eval: (Epoch 300 of 300) [0016/0020]  Time: 0.06535 (1.054)  Loss: 0.47998 (0.388)  Error: 0.89749 (0.897)

Eval: (Epoch 300 of 300) [0017/0020]  Time: 0.06668 (1.120)  Loss: 0.34982 (0.385)  Error: 0.89259 (0.897)

Eval: (Epoch 300 of 300) [0018/0020]  Time: 0.06468 (1.185)  Loss: 0.29784 (0.380)  Error: 0.89301 (0.897)

Eval: (Epoch 300 of 300) [0019/0020]  Time: 0.06477 (1.250)  Loss: 0.52827 (0.388)  Error: 0.89644 (0.897)

Eval: (Epoch 300 of 300) [0020/0020]  Time: 0.03533 (1.285)  Loss: 0.39355 (0.389)  Error: 0.89657 (0.897)
`

**Comment by stevenwudi** [comment]
Same for me here, weird.

**Comment by tryerrorman** [comment]
Yes, you are right. It works in other logic. But I haven't find the logic error here.
Thank you very much.

**Comment by tryerrorman** [comment]
I found the problem was caused by the different dimension of predictions_var and target_var.
So I change the codes from
``` python
      error = 1 - torch.eq(predictions_var, target_var).float().mean()
```
to
``` python
      error = 1 - torch.eq(predictions_var[:,0], target_var).float().mean()
```
