### ISSUE TITLE
efficient seams not so efficient.

### ISSUE THREAD

**Issue by tengshaofeng** [gpleiss/efficient_densenet_pytorch#21]
hi, @gpleiss ,
  i am so appreciate with your great job. but when i try your code on 448*448 images,  depth of 40 net can
not work with batch size of 10.  so it  will  not be trained on depth of 101.  my gpu is 11GB.
can you help me?

**Comment by gpleiss** [comment]
448 x 448 images are rather large, so this may be reasonable behavior.

**Comment by tengshaofeng** [comment]
ok, thanks
