### ISSUE TITLE
Could it be MORE memory efficient?

### ISSUE THREAD

**Issue by zhiqiangdon** [gpleiss/efficient_densenet_pytorch#22]
Hi,

Thanks for your code. I read both the single-gpu and multi-gpus codes. For the single-gpu version, you create the shared memory inside each dense block. Could all the dense blocks share the same memory and you only allocate one block of space? I think it should further reduce the space usage.

For the multi-gpus version, you create the shared memory in the initialization method of the whole network, i.e. one level upper the dense block initialization. However, you register a buffer inside each dense block for the shared memory, which is done by 
`self.register_buffer('CatBN_output_buffer', self.storage)`
Does this mean each dense block has independent shared memory? If so, why don't you let them share the same area?

Thanks

**Comment by taineleau** [comment]
You're right.

**Comment by zhiqiangdon** [comment]
Thanks @taineleau,

For the single-gpu code, I tried to modify it to make the _EfficientCat and _EfficientBatchNorm to use one block of space. The code could run. However, for the first several iterations, the accuracy keeps decreasing. When I use code without this modification, the accuracy has the trend of increasing. It seems wired. Do you have any hint?

**Comment by taineleau** [comment]
Hi, thanks for your trial! First of all, does your modified version pass all the tests (under PyTorch 0.12)? I am currently busy writing my Ph.D. application. Would like to take a look after 15 Dec.

**Comment by zhiqiangdon** [comment]
@taineleau Sorry for the late reply. I didn't test on all tests. Actually, I use the efficient dense connection in my own method which is for a different task. The performance I observe is from my own task.
