### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by EliasVansteenkiste** [gpleiss/efficient_densenet_pytorch#23]
Any plans to make pretrained models available?
Or is it possible to use the pretrained models from https://github.com/liuzhuang13/DenseNet#results-on-imagenet-and-pretrained-models?

Thanks in advance,

**Comment by taineleau** [comment]
Hi, 
It should be easy to achieve if you follow some [example code](https://github.com/clcarwin/convert_torch_to_pytorch).

**Comment by gpleiss** [comment]
See #13. @ZhengRui made some pretrained models, available here: https://drive.google.com/file/d/0B3aawkjLrbgMbWZxSmlDeXhFV3c/view
