### ISSUE TITLE
Input data size

### ISSUE THREAD

**Issue by g5996706** [gpleiss/efficient_densenet_pytorch#30]
Hi, thanks for this efficient densenet code.
I have some problems.
I try to use different input data size to train the model,
If the size is smaller than 64 * 64 that will be no problem
but if the size is bigger than 64 * 64  the errors will appear.
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:247
Can you point me how to fix it?
Thank you so much.

**Comment by gpleiss** [comment]
@g5996706 this model is a classification model, so it's designed to take inputs of fixed size. With `small_inputs=True` (the default option) passed to the constructor (See the [docstring](https://github.com/gpleiss/efficient_densenet_pytorch/blob/master/models/densenet_efficient.py#L156)), the network is designed to handle 32x32 images, such as CIFAR or SVHN images. With `small_inputs=False`, the network is designed to handle 224x224 images, which is the standard ImageNet image size.

**Comment by g5996706** [comment]
Thank you for your answer.
If I want to use the 224 * 224 as input ,in addition to setting small_inputs=False ,
should I change any other places?

**Comment by gpleiss** [comment]
Yes `avgpool_size` should become 7. You should also use a `block_config` with 4 blocks, rather than 3.
