### ISSUE TITLE
not worked in python3 environment

### ISSUE THREAD

**Issue by tengshaofeng** [gpleiss/efficient_densenet_pytorch#37]
hi , it worked when in python2 environment, but failed in python3.
 
*** Error in `/home/tengbq/.virtualenvs/py3/bin/python': free(): invalid next size (fast): 0x00007f5f8d34c3b0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f640b7e57e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7fe0a)[0x7f640b7ede0a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f640b7f198c]
/usr/local/cuda-8.0/lib64/libcudnn.so.6(cudnnDestroyConvolutionDescriptor+0x9)[0x7f63772f4c69]
/home/tengbq/.virtualenvs/py3/local/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so(+0x2dfe17)[0x7f6364044e17]
/home/tengbq/.virtualenvs/py3/local/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so(_ZN5torch5cudnn30cudnn_convolution_full_forwardEP8THCStateP12cudnnContext15cudnnDataType_tPNS_12THVoidTensorES7_S7_S7_St6vectorIiSaIiEESA_SA_ibb+0x6a4)[0x7f6364f16834]
/home/tengbq/.virtualenvs/py3/local/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so(_ZN5torch8autograd11ConvForward5applyERKSt6vectorINS0_8VariableESaIS3_EE+0x1192)[0x7f6364287712]
/home/tengbq/.virtualenvs/py3/local/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so(+0x410c7e)[0x7f6364175c7e]
/home/tengbq/.virtualenvs/py3/bin/python(_PyObject_FastCallDict+0x8b)[0x55a279d841bb]
/home/tengbq/.virtualenvs/py3/bin/python(+0x19cd3e)[0x55a279e11d3e]
/home/tengbq/.virtualenvs/py3/bin/python(_PyEval_EvalFrameDefault+0x30a)[0x55a279e3619a]
/home/tengbq/.virtualenvs/py3/bin/python(+0x1959a6)[0x55a279e0a9a6]
/home/tengbq/.virtualenvs/py3/bin/python(+0x196a11)[0x55a279e0ba11]

**Comment by gpleiss** [comment]
It works for me in python 3.6 (on various machines)
That stack trace looks like it might be an issue with your PyTorch installation?

**Comment by tengshaofeng** [comment]
pytorch is no problem.  and my torch version is 0.3.1.
some one said that maybe malloc but use delete, or new but use free .  
经查，这通常发生在C/C++混合编程时候调用的内存分配、释放接口不配对时。

即malloc分配的内存，却用了delete或者new出来的对象，却用了free.

只要确保：malloc/free new/delete配对，该问题就消失了。

**Comment by gpleiss** [comment]
This model only works with PyTorch 0.4, as it says in the Readme.
