### ISSUE TITLE
Eliminate reduce() ?

### ISSUE THREAD

**Issue by cclauss** [gpleiss/efficient_densenet_pytorch#4]
The reduce() function was dropped in Python 3.  https://docs.python.org/3.0/whatsnew/3.0.html#builtins  There is still an [implementation in functools](https://docs.python.org/3/library/functools.html#functools.reduce) but the advise is to use a loop instead.   How should https://github.com/gpleiss/efficient_densenet_pytorch/blob/master/models/densenet_efficient.py#L146 be modified to work in both Python 2 and Python 3?

**Comment by gpleiss** [comment]
My bad! The fix is now pushed in master. I tested that it works in Python 3.6.
