### ISSUE TITLE
Can't not train when using a 256*256 dataset

### ISSUE THREAD

**Issue by nessieyang** [gpleiss/efficient_densenet_pytorch#42]
I can run the network by using CIFAR-10 as my dataset.
However, when I use my own dataset which has the size of 256*256 , it can not work.
I tried to transform my data into 32*32, it also works.
So how can I solve the scaling problem?

**Comment by gpleiss** [comment]
Set `small_inputs=False` in the [model constructor](https://github.com/gpleiss/efficient_densenet_pytorch/blob/master/models/densenet.py#L89).

**Comment by gpleiss** [comment]
`small_inputs=True` expects 32 x 32 images. `small_input=False` expects 224 x 224.
