### ISSUE TITLE
torch.utils.checkpoint cost too much memory than previous 0.3 version

### ISSUE THREAD

**Issue by mingminzhen** [gpleiss/efficient_densenet_pytorch#44]
Hi,
I test the 0.4 version. I find out that the torch.utils.checkpoint cost more memory than your implementation on pytorch0.3 by using torch._C._cudnn_batch_norm_forward. 
But i can not find the similar functions like torch._C._cudnn_batch_norm_forward in 0.4.
Do you want to implement it for pytorch0.4?

**Comment by gpleiss** [comment]
In this repo, I'm not planning on implementing functions like `torch._C._cudnn_batch_norm_forward`. I want this implementation to be stand-alone (without requiring building/compiling).

It wouldn't be too difficult to write thin C wrappers that implement `torch._C._cudnn_batch_norm_forward`, but then you wouldn't be able to use the efficient model without additional installation.
