### ISSUE TITLE
Validation dataset is being augmented as well

### ISSUE THREAD

**Issue by garyfanhku** [gpleiss/efficient_densenet_pytorch#51]
Thanks for the great repo! Just found out that transformation was applied prior to train val split, effectively augmenting validation set. I don't have a neat solution for this but maybe this gist  https://gist.github.com/kevinzakka/d33bf8d6c7f06a9d8c76d97a7879f5cb could be a way out, although it has to load twice the same data.

**Comment by gpleiss** [comment]
Thanks for the catch. This has been updated with b0a156d87b736d90c3e27933e8e4d0114bd5ef36
