### ISSUE TITLE
New adaptive pooling layer.

### ISSUE THREAD

**Issue by CielAl** [gpleiss/efficient_densenet_pytorch#56]
It appears that models in the torchvision are now using adaptive poolings: `adaptive_avg_pool2d `
 to break the tie to the input size: [vision/densenet.py](https://github.com/pytorch/vision/blob/master/torchvision/models/densenet.py#L115)
 
Perhaps that simplify the constructor a little bit and generalize the usage even more?

**Comment by gpleiss** [comment]
That sounds good. Would you be willing to put up a PR?
