### ISSUE TITLE
About mean and stdv

### ISSUE THREAD

**Issue by xycoco** [gpleiss/efficient_densenet_pytorch#7]
Hi, 
In [demo.py#L212](https://github.com/gpleiss/efficient_densenet_pytorch/blob/master/demo.py#L212), the mean value and stdv value are given directly:
```
mean = [0.5071, 0.4867, 0.4408] 
stdv = [0.2675, 0.2565, 0.2761]
```

but when I use the [compute-cifar10-mean.py](https://github.com/bamos/densenet.pytorch/blob/master/compute-cifar10-mean.py) to calculate them, I get the result as follows:
```
means: [0.53129727, 0.52593911, 0.52069134]
stdevs: [0.28938246, 0.28505746, 0.27971658]
```

these two results are different obviously, can you tell me how to calculate the mean and stdv in original demo?

Thanks!

**Comment by taineleau** [comment]
@xycoco I am not familiar with Bamos' code, but I guess it's [a known issue](http://tsong.me/blog/numpy-std/)that numpy will suffer from the precision problem if use `float32` in `np.std()`.

**Comment by xycoco** [comment]
@taineleau Thanks for your reply. 
When I check Bamos' code, I found his data shape is caffe's format `[batch, channel ,width, height]`, which is different from the pytorch format.
