### ISSUE TITLE
The function received no value for the required argument: data

### ISSUE THREAD

**Issue by June-Luo** [gpleiss/efficient_densenet_pytorch#72]
I run the demo.py,but i got the error "The function received no value for the required argument: data".It seems like have something to do with fire.How can i solve tist problem.

**Comment by gpleiss** [comment]
I think you must've forgotten the `--data` command line argument, which is required.

```sh
CUDA_VISIBLE_DEVICES=0 python demo.py --efficient True --data <path_to_folder_with_cifar10> --save <path_to_save_dir>
```

**Comment by June-Luo** [comment]
Yes, that's the problem. Now I've solved it. Thank you very much！
